spring.application.name=appLibraryBackend
#configurar las credenciales para la conexión a la base dblibrary
spring.datasource.url=jdbc:mysql://localhost:3306/dblibrary

#credencial para el usuario con el que nos vamos a conectar
spring.datasource.username=root

#password
spring.datasource.password=

#configurar el driver de mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#configurar a Hibernate para que actualice la base de datos
spring.jpa.hibernate.ddl-auto=update

#Mostrar las intrucciones de SQL al ejecutarlas no obligatorio cuando se realizaron todas las pruebas
#es mientras estamos en desarrollo
spring.jpa.show-sql=true